【镜像配置】:
  域名: "{当前域名}"
  目标: "{随机目标站}"
  核心词: "{关键词1}"
  模板: "{随机模板}"

【首页TDK】:
  转码: false
  标题: "{自定义标题}"
  关键词: "{关键词1}"
  描述: "{自定义描述}"

【内页TDK】:
  转码: true
  标题: "{自定义标题}"
  关键词: "{关键词1}"
  描述: "{自定义描述}"

【全局替换】:
  转码: true
  单行替换:
    - 待替换字符串 -> 替换词
  多行替换: |-
    `待替换字符串可以多行``替换词`
    r`<正则可用>.*?</正则可用>``替换词`

【首页替换】:
  转码: false
  单行替换:
    - 待替换字符串 -> 替换词
  多行替换: |-
    `待替换字符串可以多行``替换词`
    r`<正则可用>.*?</正则可用>``替换词`

【内页替换】:
  转码: false
  单行替换:
    - 待替换字符串 -> 替换词
  多行替换: |-
    `待替换字符串可以多行``替换词`
    r`<正则可用>.*?</正则可用>``替换词`