【镜像配置】:
  域名: localhost
  目标: http://www.hzslgzx.com/
  核心词: 靠谱的菠菜平台

【首页TDK】:
  转码: false
  标题: 靠谱的菠菜平台|lol靠谱菠菜大平台
  关键词: 靠谱的菠菜平台,lol靠谱菠菜大平台
  描述: 靠谱的菠菜平台是莘莘学子放飞梦想，实现理想，成就人生的热土。lol靠谱菠菜大平台以“励志、求真、开拓、奋进”为治校兴教理念，着力实施“德为首、质为先、人为本”的办学宗旨，靠谱的菠菜平台形成了“文明、勤勉、务实、奉献”的优良校风。“潮平两岸阔，风正一帆悬。”lol靠谱菠菜大平台正在以新的校园规划为起点，以精细化管理为抓手，以打造有效课堂为着力点，以“树裕安教育标杆，创和谐奋进校园，打造江淮名校”为目标，凝心聚力，开拓进取，共同铸造新中更加辉煌的明天。

【内页TDK】:
  转码: true
  标题: "{自定义标题}"
  关键词: "{关键词1}"
  描述: "{自定义描述}"

【全局替换】:
  转码: false
  单行替换:
    - 齐师掠影 -> 靠谱的菠菜平台
  多行替换: |-
    `关键词可以多行``替换词`
    r`<正则可用>.*?</正则可用>``替换词`

【首页替换】:
  转码: false
  单行替换:
    - 关键词 -> 替换词
    - 江苏扬子晚报 -> 靠谱的菠菜平台
  多行替换: |-
    `关键词可以多行``替换词`
    r`<正则可用>.*?</正则可用>``替换词`

【内页替换】:
  转码: false
  单行替换:
    - 关键词 -> 替换词
    - '<div class="tit2"> -> <div class="tit2">{关键词1} '
  多行替换: |-
    `<p>地址：南京市建邺区江东中路369号新华报业传媒广场　邮编：210092　联系我们：025-96096(24小时)</p>　</div>
    <p>互联网新闻信息服务许可证32120170004 视听节目许可证1008318号``替换词`
    r`<正则可用>.*?</正则可用>``替换词`